
recon_task:
  description: >
    Gather information about the target's network and systems
    Make sure to include IP addresses, domain names, and running services.
  expected_output: >
    A list with the most relevant information about the target's network and systems
  agent: recon_agent

port_scan_task:
  description: >
    Identify open ports and services on the target's systems
    Make sure to include the most relevant information about the target's network and systems
  expected_output: >
    A list with the most relevant information about the open ports and services on the target's systems
  agent: port_scan_agent

vuln_scan_task:
  description: >
    Analyze scan results to identify known vulnerabilities
    Make sure to include the most relevant information about the target's network and systems
  expected_output: >
    A list with the most relevant information about the known vulnerabilities on the target's systems
  agent: vuln_scan_agent

exploit_task:
  description: >
    Attempt to exploit the identified vulnerabilities to gain access to the target system
    Make sure to include the most relevant information about the target's network and systems
  expected_output: >
    A list with the most relevant information about the exploited vulnerabilities on the target's systems
  agent: exploit_agent

post_exploit_task:
  description: >
    Gather information about the target's network and systems after exploitation
    Make sure to include IP addresses, domain names, and running services.
  expected_output: >
    A list with the most relevant information about the target's network and systems after exploitation
  agent: post_exploit_agent

report_task:
  description: >
    Create a detailed report based on the analysis and research findings
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

